### PR TITLE
add file()

### PR DESCRIPTION
**Pull request by danielb2**

### CODE REVIEW

**Comment by cjihrig** [comment]
I really don't like this for a few reasons. `file()` can't differentiate between files and directories. `fs.existsSync()` is a deprecated API. But most importantly, I don't think `Code` should have file system operations built into it.

**Comment by danielb2** [comment]
How about exposing `addMethod` so it's easy to make custom validations?

**Comment by cjihrig** [comment]
I don't think just exposing `internals.addMethod()` would work. If we went that route, I'd want it to ideally be:

- A new function that wraps `internals.addMethod()`.
- Properly sets `this`, so that `this.assert()`, `this._ref`, etc. are available.
- Throws if you attempt to redefine an existing check.

**Comment by danielb2** [comment]
Yeah, that's what I was thinking. Would you accept a PR for that?

**Comment by danielb2** [comment]
btw, I would rename this._ref to not have underscore since it would be a public api.

**Comment by gergoerdosi** [comment]
I think that would go again the main principle of this module:

> The second reason is that similar to lab, our test runner, we wanted an assertion library that is small, simple, and intuitive - without plugins, extensions, or the overhead of having to support testing in the browser.

**Comment by danielb2** [comment]
addMethod would keep it small yet make it extendable for more functionality. I don't see how that goes against the principle at all

**Comment by cjihrig** [comment]
I don't hate the idea of allowing user defined assertions. It could help keep `Code` small by limiting requests such as the one in this PR. However, you're going to have to write (more or less) the same code anyway. I'd like to get @hueniverse's opinion on this.

**Comment by hueniverse** [comment]
I am generally opposed to extensible api here. It's not like you can't write utilities on top of this already. The whole point of code was to get away from the shit show that's all the other assertion modules.

**Pull request closed without merging**
