### PR TITLE
Use JSDoc comments

### PR DESCRIPTION
**Pull request by thibaultboursier**
I think it's useful to have some JSDoc comments all over functions, so I added it. We can see directly the expected parameter types and what the function returns.

I also added the possibility to generate some documentation files with JSDoc module.

### CODE REVIEW

**Comment by cjihrig** [comment]
Thanks for opening this, but I'm going to pass. I personally find code much harder to read with these comments all over them, and we already have API docs.

**Comment by thibaultboursier** [comment]
I understand your point of view. On the other hand, it is true that one does not understand systematically the type of parameter expected when one discovers this library, and the naming of the variables does not help forcibly. Do you have other ideas? Thank you for your review.

**Comment by cjihrig** [comment]
The API docs would be a better place to listing the expected types. Are there any specific places that you find confusing? Most of the library is just passing in any value and then calling a function with no arguments (`expect(foo).to.be.a.boolean()`).

**Comment by thibaultboursier** [comment]
Thank you for your answer, Colin. Indeed, the docs API is a good place to list the expected types. However, I think it has more of a place near the code. When we start to develop on a module, in my opinion, we must have as many indications as possible near the code, without necessarily opening another document. Question of perspective :-)

**Pull request closed without merging**
