### PR TITLE
Very very basic typescript typings

### PR DESCRIPTION
**Pull request by faceleg**

### CODE REVIEW

**Comment by hueniverse** [comment]
This requires a wider discussion in hapijs/discuss about adding these files.

**Comment by faceleg** [comment]
Please could you ping the relevant parties?

**Comment by gergoerdosi** [comment]
There is already a definition here which seems to be maintained:

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/hapi

**Comment by cjihrig** [comment]
Closing until the aforementioned wider discussion happens.

**Comment by faceleg** [comment]
@gergoerdosi this is for hapi, not code

**Comment by faceleg** [comment]
@cjihrig could you let us know where this discussion is going to take place? I'm sure a lot of us would like to read it.

**Comment by cjihrig** [comment]
> This requires a wider discussion in hapijs/discuss about adding these files.

Someone will need to start the discussion there.

**Pull request closed without merging**
