### PR TITLE
Invalidates rejection with wrong type or message arguments

### LINKED ISSUE #119: reject does not fail if argument is of the wrong type
I expected the following test to fail:
```javascript
it('should fail', async () => {
        const promise = Promise.reject(new Error('some error message'));
        await expect(promise).to.reject(Error, {});
        await expect(promise).to.reject(Error, []);
        await expect(promise).to.reject(Error, null);
        await expect(promise).to.reject(Error, undefined);
        await expect(promise).to.reject(Error, NaN);

});
```
But surprisingly it does not. From the documentation, it is clear that the second argument to `reject()` needs to be a string or a regex, but would it not be safer to make the test fail if that is not the case?

### PR DESCRIPTION
**Pull request by ferrao**
Fixes #119

### CODE REVIEW

**Comment by cjihrig** [comment]
This is a step in the right direction. I think the type checking and argument parsing in general still has a way to go. For example:

```js
await Code.expect(Promise.reject(new Error('kaboom'))).to.reject(NaN);
```

`NaN` and a number of other falsey values don't cause this code to fail.

**Comment by ferrao** [comment]
@cjihrig I just tackled the problem that I noticed/was having, which was the `message` argument having a type different from `string` or `regex`. I did not realised the `type` argument had issues as well, will take a stab at it and resubmit again.

**Comment by ferrao** [comment]
@cjihrig, just pushed a new commit to check the type argument as well.

**Comment by ferrao** [comment]
@cjihrig do you think the current checks and tests are sufficient?

**Pull request merged**
